name = CHIP8Processor
description = Provides a complete Sleigh specification for the CHIP-8 instruction set to enable correct disassembly and decompilation in Ghidra.
author = Chase Prasad, Cher Huang, Murali Lingamsetty
createdOn = 2025-11-24
version = 11.4.2
ghidra.version = 11.4.2
extension.priority = 10
